/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;
import control.*;
import model.*;
import java.awt.Color;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaAgregarAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarAutomovil
     * Y la hacemos visible
     */
    public VentanaAgregarAutomovil() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Agregar Automovil");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblAutomovil = new javax.swing.JLabel();
        jLblMarca = new javax.swing.JLabel();
        jLblModelo = new javax.swing.JLabel();
        jLblEstadoActual = new javax.swing.JLabel();
        jLblPlaca = new javax.swing.JLabel();
        jLblKilometraje = new javax.swing.JLabel();
        jTxtFieldMarca = new javax.swing.JTextField();
        jTxtFieldModelo = new javax.swing.JTextField();
        jTxtFieldEstado = new javax.swing.JTextField();
        jTxtFieldKilometraje = new javax.swing.JTextField();
        jTxtFieldPlaca = new javax.swing.JTextField();
        jBtnReestablecer = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblAutomovil.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblAutomovil.setText("Agregar Automovil");

        jLblMarca.setText("Marca:");

        jLblModelo.setText("Modelo:");

        jLblEstadoActual.setText("Estado Actual:");

        jLblPlaca.setText("Placa:");

        jLblKilometraje.setText("Kilometraje:");

        jTxtFieldMarca.setText("Introduzca la marca");

        jTxtFieldModelo.setText("Introduzca el modelo");

        jTxtFieldEstado.setText("Introduzca el estado actual");

        jTxtFieldKilometraje.setText("Introduzca el kilometraje");

        jTxtFieldPlaca.setText("Introduzca la placa");

        jBtnReestablecer.setText("Reestablecer");
        jBtnReestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReestablecerMouseClicked(evt);
            }
        });

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGuardarMouseClicked(evt);
            }
        });

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblModelo)
                            .addComponent(jLblKilometraje)
                            .addComponent(jLblPlaca)
                            .addComponent(jLblEstadoActual)
                            .addComponent(jLblMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblAutomovil)
                        .addGap(57, 57, 57)))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnReestablecer)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnGuardar)
                        .addGap(40, 40, 40))
                    .addComponent(jBtnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblAutomovil)
                .addGap(2, 2, 2)
                .addComponent(jBtnCerrar)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarca)
                    .addComponent(jTxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblModelo)
                    .addComponent(jTxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEstadoActual)
                    .addComponent(jTxtFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblKilometraje)
                    .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPlaca)
                    .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReestablecer)
                    .addComponent(jBtnGuardar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//cierra la ventana
    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked
//limpia los campos
    private void jBtnReestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReestablecerMouseClicked
        reestablecer();
    }//GEN-LAST:event_jBtnReestablecerMouseClicked
//guarda un automovil
    private void jBtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarMouseClicked

        
        //valida los kilometros
        if (esNumerico(this.jTxtFieldKilometraje.getText())
                & Double.parseDouble(this.jTxtFieldKilometraje.getText()) >= 0) {
            
            Automovil auto = new Automovil(
                    this.jTxtFieldMarca.getText(),
                    this.jTxtFieldModelo.getText(),
                    this.jTxtFieldEstado.getText(),
                    Double.parseDouble(this.jTxtFieldKilometraje.getText()),
                    this.jTxtFieldPlaca.getText(),
                    true);

            ListaAutomovil.LISTA_DE_AUTOMOVILES.add(auto);
            reestablecer();
        } else {
            this.jTxtFieldKilometraje.setText("Introduce un valor valido");
            this.jTxtFieldKilometraje.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jBtnGuardarMouseClicked

    //valida que la cadena contenga un numero
    public boolean esNumerico(String cadena) {
        try {
            double d = Double.parseDouble(cadena);
        } catch (NumberFormatException nfe) {
            this.jTxtFieldKilometraje.setText("Introduce un valor valido");
            this.jTxtFieldKilometraje.setForeground(Color.red);
            return false;
        }
        return true;
    }
    
    //limpia los campos
    public void reestablecer()
    {
        this.jTxtFieldMarca.setText("");
        this.jTxtFieldModelo.setText("");
        this.jTxtFieldEstado.setText("");
        this.jTxtFieldKilometraje.setText("");
        this.jTxtFieldPlaca.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnReestablecer;
    private javax.swing.JLabel jLblAutomovil;
    private javax.swing.JLabel jLblEstadoActual;
    private javax.swing.JLabel jLblKilometraje;
    private javax.swing.JLabel jLblMarca;
    private javax.swing.JLabel jLblModelo;
    private javax.swing.JLabel jLblPlaca;
    private javax.swing.JTextField jTxtFieldEstado;
    private javax.swing.JTextField jTxtFieldKilometraje;
    private javax.swing.JTextField jTxtFieldMarca;
    private javax.swing.JTextField jTxtFieldModelo;
    private javax.swing.JTextField jTxtFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
