/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;

import java.awt.Color;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaExito extends javax.swing.JFrame {

    /**
     * Creates new form VentanaExito
     */
    public VentanaExito() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Cliente Agregado Con Exito");
        this.jLblAlquilerExito.setText("Automovil entregado con éxito");
        this.jLblAlquilerExito.setForeground(Color.red);
        this.jLblAlquilerNumero.setVisible(false);
        this.jTxtFieldAlquilerNumero.setVisible(false);
    }
    
    public VentanaExito(int numeroAlquiler)
    {
        initComponents();
        this.setVisible(true);
        this.jTxtFieldAlquilerNumero.setText(String.valueOf(numeroAlquiler));
        this.jTxtFieldAlquilerNumero.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblAlquilerExito = new javax.swing.JLabel();
        jLblAlquilerNumero = new javax.swing.JLabel();
        jTxtFieldAlquilerNumero = new javax.swing.JTextField();
        jBtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblAlquilerExito.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblAlquilerExito.setText("Alquiler Creado");

        jLblAlquilerNumero.setText("Alquiler Numero:");

        jTxtFieldAlquilerNumero.setText("5");

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jTxtFieldAlquilerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCerrar)
                    .addComponent(jLblAlquilerNumero)
                    .addComponent(jLblAlquilerExito))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblAlquilerExito)
                .addGap(39, 39, 39)
                .addComponent(jLblAlquilerNumero)
                .addGap(33, 33, 33)
                .addComponent(jTxtFieldAlquilerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jBtnCerrar)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JLabel jLblAlquilerExito;
    private javax.swing.JLabel jLblAlquilerNumero;
    private javax.swing.JTextField jTxtFieldAlquilerNumero;
    // End of variables declaration//GEN-END:variables
}
