/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaGestionarAlquiler extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionarAlquiler
     */
    public VentanaGestionarAlquiler() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Gestionar Alquiler");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGestionarAlquiler = new javax.swing.JLabel();
        jBtnCerrar = new javax.swing.JButton();
        jBtnNuevoAlquiler = new javax.swing.JButton();
        jBtnRecibirAlquiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblGestionarAlquiler.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblGestionarAlquiler.setText("Gestionar Alquiler");

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jBtnNuevoAlquiler.setText("Nuevo Alquiler");
        jBtnNuevoAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNuevoAlquilerMouseClicked(evt);
            }
        });

        jBtnRecibirAlquiler.setText("Recibir Vehiculo");
        jBtnRecibirAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRecibirAlquilerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnRecibirAlquiler)
                    .addComponent(jBtnNuevoAlquiler)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLblGestionarAlquiler)
                            .addGap(121, 121, 121))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnCerrar)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblGestionarAlquiler)
                .addGap(18, 18, 18)
                .addComponent(jBtnCerrar)
                .addGap(34, 34, 34)
                .addComponent(jBtnNuevoAlquiler)
                .addGap(32, 32, 32)
                .addComponent(jBtnRecibirAlquiler)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnNuevoAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNuevoAlquilerMouseClicked
        VentanaNuevoAlquiler vNuevoAlquiler = new VentanaNuevoAlquiler();
    }//GEN-LAST:event_jBtnNuevoAlquilerMouseClicked

    private void jBtnRecibirAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRecibirAlquilerMouseClicked
        VentanaRecibirAutomovil vRecibirautomovil = new VentanaRecibirAutomovil();
    }//GEN-LAST:event_jBtnRecibirAlquilerMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnNuevoAlquiler;
    private javax.swing.JButton jBtnRecibirAlquiler;
    private javax.swing.JLabel jLblGestionarAlquiler;
    // End of variables declaration//GEN-END:variables
}
