/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;

import model.*;
import java.awt.Color;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaMostrarAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMostrarAutomovil
     */
    public VentanaMostrarAutomovil() {
        
        String aviso;
        if(ListaAutomovil.LISTA_DE_AUTOMOVILES.size() > 0)
        {
            initComponents();
            this.setVisible(true);
            this.setTitle("Mostrar Automoviles");
            posicion = 0;
            aviso = "Automovil no disponible en rojo";
            mostrarAutomovil();
        }
        else
        {
            aviso = "No hay automoviles en el sistema";
        }
        VentanaAviso vAviso = new VentanaAviso(aviso);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblMostrarAutomoviles = new javax.swing.JLabel();
        jBtnCerrar = new javax.swing.JButton();
        jLblMarca = new javax.swing.JLabel();
        jLblModelo = new javax.swing.JLabel();
        jLblEstadoActual = new javax.swing.JLabel();
        jLblKilometraje = new javax.swing.JLabel();
        jLblPlaca = new javax.swing.JLabel();
        jTxtFieldMarca = new javax.swing.JTextField();
        jTxtFieldModelo = new javax.swing.JTextField();
        jTxtFieldEstadoActual = new javax.swing.JTextField();
        jTxtFieldKilometraje = new javax.swing.JTextField();
        jTxtFieldPlaca = new javax.swing.JTextField();
        jBtnAnterior = new javax.swing.JButton();
        jBtnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblMostrarAutomoviles.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblMostrarAutomoviles.setText("Mostrar Automoviles");

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jLblMarca.setText("Marca:");

        jLblModelo.setText("Modelo:");

        jLblEstadoActual.setText("Estado Actual:");

        jLblKilometraje.setText("Kilometraje:");

        jLblPlaca.setText("Placa");

        jTxtFieldMarca.setText("Marca");

        jTxtFieldModelo.setText("Modelo");

        jTxtFieldEstadoActual.setText("Estado");

        jTxtFieldKilometraje.setText("Kilometraje");

        jTxtFieldPlaca.setText("Placa");

        jBtnAnterior.setText("<Anterior");
        jBtnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnteriorMouseClicked(evt);
            }
        });

        jBtnSiguiente.setText("Siguiente>");
        jBtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSiguienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblEstadoActual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtFieldEstadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblKilometraje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblMostrarAutomoviles)))
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnCerrar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSiguiente)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblMostrarAutomoviles)
                .addGap(12, 12, 12)
                .addComponent(jBtnCerrar)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarca)
                    .addComponent(jTxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblModelo)
                    .addComponent(jTxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEstadoActual)
                    .addComponent(jTxtFieldEstadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblKilometraje)
                    .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPlaca)
                    .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAnterior)
                    .addComponent(jBtnSiguiente)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnteriorMouseClicked
        if(ListaAutomovil.LISTA_DE_AUTOMOVILES.size() > 1 )
        {
            --posicion;
            if(posicion < 0)
            {
                posicion = ListaAutomovil.LISTA_DE_AUTOMOVILES.size() - 1;
            }
        }
        mostrarAutomovil();
    }//GEN-LAST:event_jBtnAnteriorMouseClicked

    private void jBtnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSiguienteMouseClicked
        if(ListaAutomovil.LISTA_DE_AUTOMOVILES.size() > 1)
        {
            ++posicion;
            if (posicion == ListaAutomovil.LISTA_DE_AUTOMOVILES.size()) {
                posicion = 0;
            }
        }
        mostrarAutomovil();
    }//GEN-LAST:event_jBtnSiguienteMouseClicked

 
    public void mostrarAutomovil()
    {
        
        this.jTxtFieldMarca.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).getMarca());
        this.jTxtFieldModelo.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).getModelo());
        this.jTxtFieldEstadoActual.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).getEstadoActual());
        this.jTxtFieldKilometraje.setText(String.valueOf(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).getKilometraje()));
        this.jTxtFieldPlaca.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).getPlaca());
        
        if(!ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicion).estaDisponible())
        {
            this.jTxtFieldMarca.setForeground(Color.red);
            this.jTxtFieldModelo.setForeground(Color.red);
            this.jTxtFieldEstadoActual.setForeground(Color.red);
            this.jTxtFieldKilometraje.setForeground(Color.red);
            this.jTxtFieldPlaca.setForeground(Color.red);
        }
        
        
    }
    
    public void mostrarAutomovil(int posicionAMostrar)
    {
        this.jTxtFieldMarca.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicionAMostrar).getMarca());
        this.jTxtFieldModelo.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicionAMostrar).getModelo());
        this.jTxtFieldEstadoActual.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicionAMostrar).getEstadoActual());
        this.jTxtFieldKilometraje.setText(String.valueOf(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicionAMostrar).getKilometraje()));
        this.jTxtFieldPlaca.setText(ListaAutomovil.LISTA_DE_AUTOMOVILES.get(posicionAMostrar).getPlaca());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JLabel jLblEstadoActual;
    private javax.swing.JLabel jLblKilometraje;
    private javax.swing.JLabel jLblMarca;
    private javax.swing.JLabel jLblModelo;
    private javax.swing.JLabel jLblMostrarAutomoviles;
    private javax.swing.JLabel jLblPlaca;
    private javax.swing.JTextField jTxtFieldEstadoActual;
    private javax.swing.JTextField jTxtFieldKilometraje;
    private javax.swing.JTextField jTxtFieldMarca;
    private javax.swing.JTextField jTxtFieldModelo;
    private javax.swing.JTextField jTxtFieldPlaca;
    // End of variables declaration//GEN-END:variables

    private int posicion;
}
