/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;
import control.*;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaMostrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMostrarCliente
     */
    public VentanaMostrarCliente() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Mostrar Clientes");
        this.posicion = 0;
        mostrarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblMostrarClientes = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblAPaterno = new javax.swing.JLabel();
        jLblAMaterno = new javax.swing.JLabel();
        jLblDireccion = new javax.swing.JLabel();
        jTxtFieldNombre = new javax.swing.JTextField();
        jTxtFieldAPaterno = new javax.swing.JTextField();
        jTxtFieldAMaterno = new javax.swing.JTextField();
        jTxtFieldDireccion = new javax.swing.JTextField();
        jBtnAnterior = new javax.swing.JButton();
        jBtnSiguiente = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();
        jLblNumeroDeCliente = new javax.swing.JLabel();
        jTxtFieldNumeroDeCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblMostrarClientes.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblMostrarClientes.setText("Mostrar Clientes");

        jLblNombre.setText("Nombre:");

        jLblAPaterno.setText("Apellido Paterno:");

        jLblAMaterno.setText("Apellido Materno:");

        jLblDireccion.setText("Direccion:");

        jTxtFieldNombre.setText("Nombre");

        jTxtFieldAPaterno.setText("Paterno");

        jTxtFieldAMaterno.setText("Materno");

        jTxtFieldDireccion.setText("Direccion");

        jBtnAnterior.setText("<Anterior");
        jBtnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnteriorMouseClicked(evt);
            }
        });

        jBtnSiguiente.setText("Siguiente>");
        jBtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSiguienteMouseClicked(evt);
            }
        });

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jLblNumeroDeCliente.setText("Numero de Cliente:");

        jTxtFieldNumeroDeCliente.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblMostrarClientes)
                        .addGap(38, 38, 38)
                        .addComponent(jBtnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNombre)
                                    .addComponent(jLblAPaterno)
                                    .addComponent(jLblAMaterno)
                                    .addComponent(jLblDireccion)
                                    .addComponent(jLblNumeroDeCliente))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFieldNumeroDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jBtnAnterior)
                                .addGap(26, 26, 26)
                                .addComponent(jBtnSiguiente)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblMostrarClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBtnCerrar)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAPaterno)
                    .addComponent(jTxtFieldAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAMaterno)
                    .addComponent(jTxtFieldAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion)
                    .addComponent(jTxtFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumeroDeCliente)
                    .addComponent(jTxtFieldNumeroDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAnterior)
                    .addComponent(jBtnSiguiente)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnteriorMouseClicked
        if(VentanaPrincipal.listaDeClientes.size() > 1 )
        {
            --posicion;
            if(posicion < 0)
            {
                posicion = VentanaPrincipal.listaDeClientes.size() - 1;
            }
        }
        mostrarCliente();
    }//GEN-LAST:event_jBtnAnteriorMouseClicked

    private void jBtnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSiguienteMouseClicked
        if(VentanaPrincipal.listaDeClientes.size() > 1)
        {
            ++posicion;
            
            if(posicion == VentanaPrincipal.listaDeClientes.size())
            {
                posicion = 0;
            }
        }
        
        mostrarCliente();
    }//GEN-LAST:event_jBtnSiguienteMouseClicked

    private void mostrarCliente()
    {
        this.jTxtFieldNombre.setText(VentanaPrincipal.listaDeClientes.get(posicion).getNombre());
        this.jTxtFieldAPaterno.setText(VentanaPrincipal.listaDeClientes.get(posicion).getaPaterno());
        this.jTxtFieldAMaterno.setText(VentanaPrincipal.listaDeClientes.get(posicion).getaMaterno());
        this.jTxtFieldDireccion.setText(VentanaPrincipal.listaDeClientes.get(posicion).getDireccion());
        this.jTxtFieldNumeroDeCliente.setText(Integer.toString(VentanaPrincipal.listaDeClientes.get(posicion).getNumeroDeCliente()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JLabel jLblAMaterno;
    private javax.swing.JLabel jLblAPaterno;
    private javax.swing.JLabel jLblDireccion;
    private javax.swing.JLabel jLblMostrarClientes;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNumeroDeCliente;
    private javax.swing.JTextField jTxtFieldAMaterno;
    private javax.swing.JTextField jTxtFieldAPaterno;
    private javax.swing.JTextField jTxtFieldDireccion;
    private javax.swing.JTextField jTxtFieldNombre;
    private javax.swing.JTextField jTxtFieldNumeroDeCliente;
    // End of variables declaration//GEN-END:variables

    private int posicion;
}
