/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;

import java.awt.Color;
import model.*;
import java.awt.Font;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaGestionarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionarCliente
     */
    public VentanaGestionarCliente() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Gestionar Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGestionarCliente = new javax.swing.JLabel();
        jBtnAgregarCliente = new javax.swing.JButton();
        jBtnMostrarClientes = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblGestionarCliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblGestionarCliente.setText("Gestionar Cliente");

        jBtnAgregarCliente.setText("Agregar Cliente");
        jBtnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarClienteMouseClicked(evt);
            }
        });

        jBtnMostrarClientes.setText("Mostrar Clientes");
        jBtnMostrarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnMostrarClientesMouseClicked(evt);
            }
        });

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnMostrarClientes)
                    .addComponent(jBtnAgregarCliente)
                    .addComponent(jLblGestionarCliente))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnCerrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblGestionarCliente)
                .addGap(1, 1, 1)
                .addComponent(jBtnCerrar)
                .addGap(32, 32, 32)
                .addComponent(jBtnAgregarCliente)
                .addGap(39, 39, 39)
                .addComponent(jBtnMostrarClientes)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarClienteMouseClicked
        
        VentanaAgregarCliente ventanaAgregarCliente = new VentanaAgregarCliente();
        
    }//GEN-LAST:event_jBtnAgregarClienteMouseClicked

    private void jBtnMostrarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMostrarClientesMouseClicked
        
        if(ListaClientes.LISTA_DE_CLIENTES.size() > 0)
        {
            VentanaMostrarCliente vMostrarCliente = new VentanaMostrarCliente();
        }
        else
        {
            this.jLblGestionarCliente.setText("No hay clientes registrados");
            
            this.jLblGestionarCliente.setForeground(Color.red);
            
        }
        
    }//GEN-LAST:event_jBtnMostrarClientesMouseClicked

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarCliente;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnMostrarClientes;
    private javax.swing.JLabel jLblGestionarCliente;
    // End of variables declaration//GEN-END:variables
}
