package visual;

/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaGestionarAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAutomoviles
     */
    public VentanaGestionarAutomovil() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Gestionar Automovil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGestionarAutomovil = new javax.swing.JLabel();
        jBtnCerrar = new javax.swing.JButton();
        jBtnAgregarAutomovil = new javax.swing.JButton();
        jBtnMostrarAutomoviles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblGestionarAutomovil.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblGestionarAutomovil.setText("Gestionar Automóviles");

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jBtnAgregarAutomovil.setText("Agregar Automovil");
        jBtnAgregarAutomovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarAutomovilMouseClicked(evt);
            }
        });

        jBtnMostrarAutomoviles.setText("Mostrar Automoviles");
        jBtnMostrarAutomoviles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnMostrarAutomovilesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnCerrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnMostrarAutomoviles)
                    .addComponent(jBtnAgregarAutomovil)
                    .addComponent(jLblGestionarAutomovil))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblGestionarAutomovil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCerrar)
                .addGap(32, 32, 32)
                .addComponent(jBtnAgregarAutomovil)
                .addGap(37, 37, 37)
                .addComponent(jBtnMostrarAutomoviles)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnAgregarAutomovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarAutomovilMouseClicked
        VentanaAgregarAutomovil vAgregarAutomovil = new VentanaAgregarAutomovil();
    }//GEN-LAST:event_jBtnAgregarAutomovilMouseClicked

    private void jBtnMostrarAutomovilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMostrarAutomovilesMouseClicked
        VentanaMostrarAutomovil vMostrarAutomovil = new VentanaMostrarAutomovil();
    }//GEN-LAST:event_jBtnMostrarAutomovilesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarAutomovil;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnMostrarAutomoviles;
    private javax.swing.JLabel jLblGestionarAutomovil;
    // End of variables declaration//GEN-END:variables
}
