/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package visual;

import java.awt.Color;

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaRecibirAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRecibirVehiculo
     */
    public VentanaRecibirAutomovil() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Recibir Automovil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblRecibirAutomovil = new javax.swing.JLabel();
        jLblNumeroDeCliente = new javax.swing.JLabel();
        jLblNumeroAlquiler = new javax.swing.JLabel();
        jLblKilometraje = new javax.swing.JLabel();
        jLblIncidente = new javax.swing.JLabel();
        jBtnCerrar = new javax.swing.JButton();
        jTxtFieldNumeroCliente = new javax.swing.JTextField();
        jTxtFieldNumeroAlquiler = new javax.swing.JTextField();
        jTxtFieldKilometraje = new javax.swing.JTextField();
        jTxtFieldIncidente = new javax.swing.JTextField();
        jBtnEntregar = new javax.swing.JButton();
        jLbPlaca = new javax.swing.JLabel();
        jTxtFieldPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblRecibirAutomovil.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblRecibirAutomovil.setText("Recibir Automovil");

        jLblNumeroDeCliente.setText("Numero de Cliente:");

        jLblNumeroAlquiler.setText("Numero de Alquiler:");

        jLblKilometraje.setText("Kilometraje:");

        jLblIncidente.setText("Incidente:");

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jTxtFieldNumeroCliente.setText("2");

        jTxtFieldNumeroAlquiler.setText("5");

        jTxtFieldKilometraje.setText("100");

        jTxtFieldIncidente.setText("ninguno");

        jBtnEntregar.setText("Entregar Automovil");
        jBtnEntregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEntregarMouseClicked(evt);
            }
        });

        jLbPlaca.setText("Placa:");

        jTxtFieldPlaca.setText("abs123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLblRecibirAutomovil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEntregar)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblIncidente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFieldIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblKilometraje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNumeroAlquiler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFieldNumeroAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNumeroDeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtFieldNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jBtnCerrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblRecibirAutomovil)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNumeroDeCliente)
                            .addComponent(jTxtFieldNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jBtnCerrar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumeroAlquiler)
                    .addComponent(jTxtFieldNumeroAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblKilometraje)
                    .addComponent(jTxtFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblIncidente)
                    .addComponent(jTxtFieldIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbPlaca)
                    .addComponent(jTxtFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEntregar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnEntregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEntregarMouseClicked
        if(VentanaPrincipal.buscarAlquiler(Integer.parseInt(this.jTxtFieldNumeroAlquiler.getText()) - 1) != null)
        {
            VentanaPrincipal.buscarAutomovil(this.jTxtFieldPlaca.getText()).setDisponible(true);
            VentanaPrincipal.buscarAutomovil(this.jTxtFieldPlaca.getText()).setKilometraje(
            Integer.parseInt(this.jTxtFieldKilometraje.getText()));
            VentanaPrincipal.listaDeAlquileres.get(Integer.parseInt(this.jTxtFieldNumeroAlquiler.getText()) - 1).setEstado(false);
            reestablecer();
            VentanaExito vExito = new VentanaExito();
        }
        else
        {
            this.jTxtFieldNumeroAlquiler.setText("Introduce valores válidos");
            this.jTxtFieldNumeroAlquiler.setForeground(Color.red);
            this.jTxtFieldNumeroCliente.setText("Introduce valores válidos");
            this.jTxtFieldNumeroCliente.setForeground(Color.red);
        }
    }//GEN-LAST:event_jBtnEntregarMouseClicked

     public void reestablecer() {
        this.jTxtFieldNumeroCliente.setText("");
        this.jTxtFieldNumeroAlquiler.setText("");
        this.jTxtFieldKilometraje.setText("");
        this.jTxtFieldIncidente.setText("");
        this.jTxtFieldPlaca.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnEntregar;
    private javax.swing.JLabel jLbPlaca;
    private javax.swing.JLabel jLblIncidente;
    private javax.swing.JLabel jLblKilometraje;
    private javax.swing.JLabel jLblNumeroAlquiler;
    private javax.swing.JLabel jLblNumeroDeCliente;
    private javax.swing.JLabel jLblRecibirAutomovil;
    private javax.swing.JTextField jTxtFieldIncidente;
    private javax.swing.JTextField jTxtFieldKilometraje;
    private javax.swing.JTextField jTxtFieldNumeroAlquiler;
    private javax.swing.JTextField jTxtFieldNumeroCliente;
    private javax.swing.JTextField jTxtFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
