package visual;

import control.*;
import java.util.ArrayList;

/*
 * Copyright (C) 2016 Néstor A. M. alvarado.nestor@yandex.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *
 * @author Néstor A. M. alvarado.nestor@yandex.com
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Sistema de Alquiler");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jBtnGestionarCliente = new javax.swing.JButton();
        jBtnGestionarAutomoviles = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();
        jBtnGestionarAlquiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("Alquiler de Automóviles");

        jBtnGestionarCliente.setText("Gestionar Cliente");
        jBtnGestionarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGestionarClienteMouseClicked(evt);
            }
        });

        jBtnGestionarAutomoviles.setText("Gestionar Automóviles");
        jBtnGestionarAutomoviles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGestionarAutomovilesMouseClicked(evt);
            }
        });

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jBtnGestionarAlquiler.setText("Gestionar Alquiler");
        jBtnGestionarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGestionarAlquilerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnGestionarAutomoviles)
                            .addComponent(jLblTitulo)
                            .addComponent(jBtnGestionarCliente)
                            .addComponent(jBtnGestionarAlquiler))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnCerrar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblTitulo)
                .addGap(2, 2, 2)
                .addComponent(jBtnCerrar)
                .addGap(39, 39, 39)
                .addComponent(jBtnGestionarCliente)
                .addGap(18, 18, 18)
                .addComponent(jBtnGestionarAutomoviles)
                .addGap(18, 18, 18)
                .addComponent(jBtnGestionarAlquiler)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGestionarAutomovilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGestionarAutomovilesMouseClicked
        VentanaGestionarAutomovil vGestionarAutomovil = new VentanaGestionarAutomovil();
    }//GEN-LAST:event_jBtnGestionarAutomovilesMouseClicked

    private void jBtnGestionarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGestionarClienteMouseClicked
        
        VentanaGestionarCliente vGestionarCliente = new VentanaGestionarCliente();
        //vGestionarCliente.setVisible(true);
        
    }//GEN-LAST:event_jBtnGestionarClienteMouseClicked

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked

        this.dispose();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    private void jBtnGestionarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGestionarAlquilerMouseClicked
        VentanaGestionarAlquiler vGestionarAlquiler = new VentanaGestionarAlquiler();
    }//GEN-LAST:event_jBtnGestionarAlquilerMouseClicked

    public static Cliente buscarCliente(int numeroDeCliente)
    {
        try {
            return listaDeClientes.get((numeroDeCliente -1));
        } catch (Exception e) {
            return null;
        }

    }
    
    public static Alquiler buscarAlquiler(int numeroAlquiler)
    {
        try {
            return listaDeAlquileres.get(numeroAlquiler);
        } catch (Exception e) {
            return null;
        }
    }
    
    public static Automovil buscarAutomovil(String placa)
    {
        int posicion = -1;
        
        for(int i = 0; i < listaDeAutomoviles.size(); i++)
        {
            if(listaDeAutomoviles.get(i).getPlaca().equalsIgnoreCase(placa))
            {
                posicion = i;
            }
        }
        
        if(posicion != -1)
        {
            return listaDeAutomoviles.get(posicion);
        }
        else
        {
            return null;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnGestionarAlquiler;
    private javax.swing.JButton jBtnGestionarAutomoviles;
    private javax.swing.JButton jBtnGestionarCliente;
    private javax.swing.JLabel jLblTitulo;
    // End of variables declaration//GEN-END:variables

    public static ArrayList<Cliente> listaDeClientes = new ArrayList();
    public static ArrayList<Automovil> listaDeAutomoviles = new ArrayList();
    public static ArrayList<Alquiler> listaDeAlquileres = new ArrayList();
}
